### PR TITLE
[docs] Removes Travis CI build status badge

### LINKED ISSUE #241: Travis CI build status badge broken
## Screenshot
Screen Shot 2023-05-09 at 09 08 01

### PR DESCRIPTION
**Pull request by mnigh**
Resolves #241.

### CODE REVIEW

**Comment by delisma** [comment]
@mnigh In order to keep parity between our repo, is it possible to make the fix in `canada-ca/systeme-conception` also? Just add a link to this PR in a comment and vice-versa.

**Review by delisma — CHANGES_REQUESTED** [review]
@mnigh In order to keep parity between our repos, is it possible to make the fix in `canada-ca/systeme-conception` also? Just add a link to this PR in a comment and vice-versa.

**Comment by mnigh** [comment]
@delisma already done, see https://github.com/canada-ca/systeme-conception/pull/142.

**Review by delisma — APPROVED** [review]
LGTM

**Comment by delisma** [comment]
@mnigh A bit off-topic, are you familiar with Storybook? I'm looking for someone that has a bit of knowledge with the tool to guide me around.

**Pull request merged**
