### PR TITLE
Update monitoring.html - Link to TSS

### PR DESCRIPTION
**Pull request by LanaStewa**
Updating link to new TSS content
Once done, this page can be removed: https://design.canada.ca/continuous-improvement/monitoring/GCTSS.html

### CODE REVIEW

**Comment by pcwsmith** [comment]
NB parallel French PR is here: https://github.com/canada-ca/systeme-conception/pull/153

**Review by pcwsmith — APPROVED** [review]
everything looks gtg here, so I am approving

**Comment by pcwsmith** [comment]
@delisma it looks like you need to approve this one before it can be merged.

**Comment by LanaStewa** [comment]
Fixed the http to https error in the checks.  All good now

**Review by pcwsmith — APPROVED** [review]
not sure if this PR will actually remove the GCTSS.html page, but approving anyway since it orphans it :+)

**Comment by LanaStewa** [comment]
Preview looks ok to me!

**Pull request merged**
