### PR TITLE
Lana feedback edits

### PR DESCRIPTION
**Pull request by LanaStewa**
Note: the images aren't displaying because the branch with the new images has not been published.
FN PR: https://github.com/canada-ca/systeme-conception/pull/229

https://deploy-preview-349--design-system-canada-ca.netlify.app/feedback/when
https://deploy-preview-349--design-system-canada-ca.netlify.app/feedback/about-page-feedback

Added images to the how this works page
Added a new on this page section to the "when" page

### CODE REVIEW

**Comment by donohuech** [comment]
On this page: https://deploy-preview-349--design-system-canada-ca.netlify.app/feedback/when#how-not-to-use-the-feedback-tool

There's a "you" in here that should be "your":

**Use cases for the page feedback tool**
Consider adding the page feedback tool to:

- uncover specific page-level issues affecting **you** GC Task Success Survey task score

**Comment by donohuech** [comment]
On this page: https://deploy-preview-349--design-system-canada-ca.netlify.app/feedback/when#how-not-to-use-the-feedback-tool

There is an "is" in here that should be an "if":

**Evaluating page success based on yes / no clicks**
The feedback tool is biased towards collecting ‘no’ answers in several ways:

- Humans, by nature, have a negativity bias
- We are only collecting feedback **is** someone selects ‘no’
- If they did find an answer and were successful, they may never have reached the bottom of the page

**Comment by donohuech** [comment]
On this page: https://deploy-preview-349--design-system-canada-ca.netlify.app/feedback/when#how-not-to-use-the-feedback-tool

Missing a period at the end of this paragraph: 

**Evaluating statistical significance of feedback based on page visits**
The number of page visits does not represent the number of people who saw the feedback tool at the bottom of the page or were motivated to use it

**Comment by donohuech** [comment]
On this page: https://deploy-preview-349--design-system-canada-ca.netlify.app/feedback/about-page-feedback 

Image description for 2b should remove the "in"

After interacting with the “No” button **in**, a text entry screen will replace the prompt.

In the contact option, there is an expand/collapse pattern with the header “Need urgent help with a problem? Contact us”. When the expand/collapse pattern is opened, there is a customizable link to contact the service.

After the expand/collapse pattern, there is a heading for “Please provide more details” followed by instructions to not include personal information: “You will not receive a reply. Don’t include personal information (telephone, email, SIN financial, medical, or work details. Maximum 300 characters.” There is a small text entry box followed by a button for “Submit”.

**Review by donohuech — COMMENTED** [review]
Added comments for some small fixes @LanaStewa

**Comment by LanaStewa** [comment]
@donohuech Just pushed these edits

**Review by delisma — APPROVED** [review]

**Pull request merged**
