### PR TITLE
Testing redirects

### PR DESCRIPTION
**Pull request by prycrane**
### Testing Netlify redirects

All these pages redirect with the, you guessed it, [_redirects](https://github.com/canada-ca/design-system/blob/test-redirects/_redirects) file.  :) 

- https://deploy-preview-279--design-system-canada-ca.netlify.app/common-design-patterns/redirect-test.html
- https://deploy-preview-279--design-system-canada-ca.netlify.app/covid/alerts.html 
- https://deploy-preview-279--design-system-canada-ca.netlify.app/covid/content.html
- https://deploy-preview-279--design-system-canada-ca.netlify.app/continuous-improvement/monitoring/GCTSS.html
- https://deploy-preview-279--design-system-canada-ca.netlify.app/mandatory-templates/theme-pages.html
- https://deploy-preview-279--design-system-canada-ca.netlify.app/mandatory-templates/topic-pages.html

### CODE REVIEW

**Comment by prycrane** [comment]
@delisma - The eagle has landed!  We can do proper redirects!

**Comment by delisma** [comment]
> @delisma - The eagle has landed!  We can do proper redirects!

Awesome sauce! Can we do pattern redirect too? Like for the blog eventually. Like [blog.canada.ca]/yyyy/mm/dd/blog-title would be redirected to [design.canada.ca/blog]/yyyy/mm/dd\blog-title without having to list all 50+ blog posts..

**Comment by prycrane** [comment]
> > @delisma - The eagle has landed!  We can do proper redirects!
> 
> Awesome sauce! Can we do pattern redirect too? Like for the blog eventually. Like [blog.canada.ca]/yyyy/mm/dd/blog-title would be redirected to [design.canada.ca/blog]/yyyy/mm/dd\blog-title without having to list all 50+ blog posts..

I will look into that.  I'm pretty sure that we can...

**Comment by prycrane** [comment]
> > > @delisma - The eagle has landed!  We can do proper redirects!
> > 
> > 
> > Awesome sauce! Can we do pattern redirect too? Like for the blog eventually. Like [blog.canada.ca]/yyyy/mm/dd/blog-title would be redirected to [design.canada.ca/blog]/yyyy/mm/dd\blog-title without having to list all 50+ blog posts..
> 
> I will look into that. I'm pretty sure that we can...

I think you would need to run a process that writes to the _redirect or TOML file.  I don't think it could be handled programmatically within the file itself.  This is a pretty good case for flattening file directories.  The date directories do not add any value to the user and they create back-end complications.  Anyway, I would just list the 50+.  Not really a big deal.

**Review by delisma — COMMENTED** [review]
This request should be closed

**Comment by delisma** [comment]
> > > > @delisma - The eagle has landed!  We can do proper redirects!
> > > 
> > > 
> > > Awesome sauce! Can we do pattern redirect too? Like for the blog eventually. Like [blog.canada.ca]/yyyy/mm/dd/blog-title would be redirected to [design.canada.ca/blog]/yyyy/mm/dd\blog-title without having to list all 50+ blog posts..
> > 
> > 
> > I will look into that. I'm pretty sure that we can...
> 
> I think you would need to run a process that writes to the _redirect or TOML file. I don't think it could be handled programmatically within the file itself. This is a pretty good case for flattening file directories. The date directories do not add any value to the user and they create back-end complications. Anyway, I would just list the 50+. Not really a big deal.

I found this. I believe the `splat` option could be used on the blog to redirect everything to the design system https://docs.netlify.com/routing/redirects/redirect-options/#splats

**Pull request closed without merging**
