### PR TITLE
feat: Update institutional_landing_page_guidance.html

### PR DESCRIPTION
**Pull request by delisma**
From design-system-systeme-conception repo:

- [Accessibility issues with designs #90](https://github.com/canada-ca/design-system-systeme-conception/issues/90)
- [Accessibility: Multiple occurrences for misuse of `<section>`(Failure WCAG 1.3.1) #91](https://github.com/canada-ca/design-system-systeme-conception/issues/91)
- [Accessibility: Related links that are not grouped in a list (Failure WCAG 1.3.1) #92](https://github.com/canada-ca/design-system-systeme-conception/issues/92)
- [Accessibility : Failing sufficient contrast due to text on background image (WCAG 1.4.3) #93](https://github.com/canada-ca/design-system-systeme-conception/issues/93)
- [Accessibility : Repetitive and unclear heading text (Failure WCAG 2.4.6) #94](https://github.com/canada-ca/design-system-systeme-conception/issues/94)

### CODE REVIEW

**Review by jmealing — APPROVED** [review]

**Comment by delisma** [comment]
@jmealing I think that we can move this to live once reviewed.
https://deploy-preview-40--design-system-en.netlify.app/coded-layout/institutional_landing_page_guidance

**Comment by jmealing** [comment]
@delisma 

We'd need to update the French example at the exact same time, it uses the`beta/ilp.css` in design-system.

The background-position isn't quite right. We need upper-right so that there's some predictability. I just tried replacing it with another image, and it's anchoring it off-screen.

Screen Shot 2020-07-14 at 3 24 49 PM

**Comment by delisma** [comment]
> The background-position isn't quite right. We need upper-right so that there's some predictability. I just tried replacing it with another image, and it's anchoring it off-screen.

This is fixed.

**Comment by jmealing** [comment]
@delisma The hide classes aren't working
Screen Shot 2020-07-14 at 4 19 40 PM

**Comment by jmealing** [comment]
@delisma `xs-left ` isn't working either
Screen Shot 2020-07-14 at 5 23 33 PM

**Pull request merged**
